[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit BME680 Library
  adafruit/Adafruit ADXL345
  adafruit/Adafruit Unified Sensor
  adafruit/RTClib
